### ISSUE TITLE
Current Price not updating for member restricted sales

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#1013]
Current Price and the 'price' in the api field does not seem to be updated for any member restricted sales.

Updated correctly:
https://soonaverse.com/nft/0x61f24030d5f1cbbfa211ad9d20ffc008f363db83

Updated missing the latest price:
https://soonaverse.com/nft/0x8cfd21ac824653dd2a1c49c05237488ed964c9a2

**Comment by ivanbeerlama** [comment]
Probably a side effect from protection on updating the price on 1Mi member restricted sales that are currently done to transfer NFTs between members.

**Comment by adamunchained** [comment]
This is done on purpose. If NFT sale is to specific member it does not change the price of the NFT. Do you think this should this be changed?

**Comment by adamunchained** [comment]
note: It has been like this since it was launched.

**Comment by ivanbeerlama** [comment]
Maybe only if it was sold for more than the previous price?

**Comment by adamunchained** [comment]
Right, what happens if price is simply declining? I don’t think we can just choose one direction…

I guess we can simply remove it and price always changes. If they want to give the NFT for 1Mi without affecting price they can just transfer it through Firefly which already has NFT support coming up.

Agree?

**Comment by adamunchained** [comment]
stale issue, closing... If you feel it should be re-open with particular solution, please feel free to reopen the issue.
