### ISSUE TITLE
Some users not recieving airdrops from user-created token

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#1024]
The following project reports that some users are not receiving airdrop rewards from the token's scheduled airdrop. The project has verified that the token distribution .csv says that those users should have tokens, but they can't see any.

https://soonaverse.com/space/0x63b87696b5d69b582e27a60fbeecb879df25fa65/overview

**Comment by adamunchained** [comment]
some or all? They don't see option to claim them?

**Comment by adamunchained** [comment]
@boldizsar-unchained - upon investigation I figure out the issue.

Guardian that performed the airdropped didn't the the ETH Addresses in lower cases within the Airdrop. We always make sure ETH Addresses are converted to lower case but it seems in case of Airdrop we don't. 

We should always convert ETH addresses to lower case.

Please can you do a fix on this as well as you will have to update the distribution records.

<img width="563" alt="Screenshot 2023-01-24 at 10 48 11 AM" src="https://user-images.githubusercontent.com/130610/214382218-0c237a94-a303-4f9e-9f37-b356a3af4b59.png">

@SeanTMartin - this will most likely be fixed by tomorrow.

**Comment by adamunchained** [comment]
Note you might have to correct:
- [ ] distribution records
- [ ] airdrop records as well

See airdrop record where member id is wrong:
```
{
  "0x81fd8870b017ed5c9135d3fbc4df1973a12ed855": {
    "count": 70000000,
    "createdBy": "0x2fea5b277e4a11406664691ac4a5315e6912ddc1",
    "createdOn": {
      "__time__": "2023-01-24T17:02:29.304Z"
    },
    "member": "0x001AEF8094d70668247333c646A8e8Ecfd619890",
    "status": "unclaimed",
    "token": "0x701e62f301748d9443e480a53ccdf360c592257c",
    "uid": "0x81fd8870b017ed5c9135d3fbc4df1973a12ed855",
    "updatedOn": {
      "__time__": "2023-01-24T17:02:29.304Z"
    },
    "vestingAt": {
      "__time__": "2023-01-23T23:00:00.000Z"
    },
    "wenUrl": ""
  }
}
```

**Comment by CptBananu** [comment]
Hi @adamunchained.
When this will probably be fixed tomorrow, is there any further action needed from the guardian like uploading a new Airdrop-List? Or will the "skipped" receivers just get their tokens a bit later?

**Comment by adamunchained** [comment]
Nothing to do for the guardian, it’ll just be fixed and all airdrop recipients will see their airdrop under their profile. We’re already working on this.

**Comment by Tanglebeast** [comment]
Thanks. Great Team!

**Comment by adamunchained** [comment]
@CptBananu / @Tanglebeast - this has now been fixed and deployed in production.
