### ISSUE TITLE
Wrong total price in Payment Window for buying a NFT

### ISSUE THREAD

**Issue by Id-IOTA** [soonaverse/soonaverse-dao#1029]
**Describe the bug**
While trying to mint one of the giveaway TangleSwap NFTs here: https://soonaverse.com/nft/0x841d94099c928456627abc1b61572b2b6a42b8ba it shows price 1SMR. If you proceed with trying to buy it, it shows the price as 0,01 SMR. The correct price was 1 SMR. Firefly copies the correct price
![grafik](https://user-images.githubusercontent.com/94924023/214912295-6add1f24-0993-4018-b17f-58a0ca01d6c9.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11
 - Firefox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adamunchained** [comment]
When you minted the collection you've actually set new price for the nft to 0.01 SMR. Hence it shows 0.01. I've correct the data and it should show correct price now.

Outside of modal it shows 1 SMR because UI assumes price can never be below 1 SMR.

We have a validation issue on set new price during minting of a collection. We should not allow <MIN_IOTA_AMOUNT - @boldizsar-unchained please add this and do a hot fix.

**Comment by adamunchained** [comment]
this has been fixed in prod few days back.
