### ISSUE TITLE
Arabic translation not showing

### ISSUE THREAD

**Issue by JM0unir** [soonaverse/soonaverse-dao#652]
**Describe the bug**
Arabic translation is not showing on the website when selected, 

**To Reproduce**
1. Go to soonaverse.com
2. Click on AR
![image](https://user-images.githubusercontent.com/39354686/163888878-2211cfc5-28b4-4214-be5b-a2e94440aaf2.png)

3. See error : English text remains in place

**Expected behavior**
Majority of website strings should switch to arabic as translated on crowdin

**Screenshots**
![image](https://user-images.githubusercontent.com/39354686/163889131-e3e344cb-1bd1-479c-9517-904a337365b0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome
 - Version 100.0.4896.88

**Smartphone (please complete the following information):**
 - Device: 
 - OS: Android 12
 - Browser: Firefox
 - Version: latest

**Comment by Gundavri** [comment]
@adamunchained There were 2 AR translations in the locale folder. ar-SA had translated strings in it but ar-EG didn't. "Ar" in the language-switch component was for ar-EG so that's why it was not translated. Now I added both versions to switch components and configs. Once you put translations in ar-EG too I think it will work fine.
