### ISSUE TITLE
Merge Collections

### ISSUE THREAD

**Issue by humaint** [soonaverse/soonaverse-dao#653]
### Discussed in https://github.com/soonlabs/soonaverse-dao/discussions/620

<div type='discussions-op-text'>

<sup>Originally posted by **LordSciFi** April 11, 2022</sup>
As one of the early NFT creators on the Soonaverse I had to/will have to split up one NFT collection into several NFT collections.

For example:
I create an NFT collection for sale but I also have to hold back the airdrops and create a separate collection for them.
Now my NFT collection is split into two different collections (sale & giveaways).
They both have their own floor prices and the NFTs are not represented as a collection that belongs together.
From an end user perspective: One has to go through several collections to find what he is looking for.

We would love to see a feature to bring these scattered NFT collections together in the way they belong.

May just add a "Connect Collection" button on the page where NFT creators can edit their collection?</div>

**Comment by humaint** [comment]
I agree, from the user perspective, it's about adding button "Merge Collection" on a collection which is sold out

**Comment by JM0unir** [comment]
I see an issue with simply addind a "Merge collection" : what's stopping a creator from creating a collection, advertising a certain number of NFTs (say 500), and then keep creating and merging collections, effectively diluting the first 500 ones ?

Maybe the "Merge collection" should not be unavailable to Limited collections, to avoid the before-mentioned situation.

**Comment by humaint** [comment]
https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=3504%3A36931

![SCR-20220426-nw0.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/6f695e8e-679e-4b96-86b0-3da0fff03711)

**Comment by humaint** [comment]
merge button on a collection where you can select other collections - these will than merge into the initial collection

- base collection can't be limited
- all collections are from the same space
- merging collections are sold out

**Comment by ledgerdevelop** [comment]
Hi, as it is not possible to expand a collection that was created as generated ( which are most of the collections ), one is forced to split the collection in multiple and therefor the feature of merging collections is highly anticipated. Please reconsider the priority. Thx a lot.

**Comment by LordSciFi** [comment]
Hi there me checking in on this feature I requested back in April in this discussion: 
https://github.com/soonaverse/soonaverse-dao/discussions/620 

Just to give you a little more perspective we, as an example, announced 11'111 Magic Voodoo Doll NFTs back in march and we plan to always do it in the same manner as we started where we have 3 sets:
1. Pre-Sale
2. Set 1
3. Set 2

To raise prices gradually. There fore it would be really cool if creators can simply create a "Master Collection" and then link the loose collections to the master collection. It would also make the rating and sorting process way more simple and cleaner (i elaborated here: https://github.com/soonaverse/soonaverse-dao/discussions/978). Meaning instead of having 3 collections of one creator in the top 10 you would have 1 collection in the top 10, leaving room for others.

Looking forward to how this will evolve, i'm at your disposal on discord,
Lord_SciFi | Magic Meme Money#9875
