### ISSUE TITLE
User is not selectable from user list to sell NFT

### ISSUE THREAD

**Issue by centercirclesolutions** [soonaverse/soonaverse-dao#746]
**Describe the bug**
MySparta is not selectable in the user list to sell an NFT to. Not sure why. Others have had this issue

![Screenshot_20220529-064517](https://user-images.githubusercontent.com/44786846/170872498-961936f9-f696-4730-a1d6-3a01df978d15.png)

**Comment by adamunchained** [comment]
Did you try to select by ID? Did that work?

**Comment by Doenermaker** [comment]
To add some others with the same issue and more informations:
BitcoinDan reported the issue on the soonlabs discord https://discord.com/channels/892481940953915433/917930917710925864/979759082401587240
The account was created nov. 21 and the functionality has worked before.

Sanderinho experienced this bug as well, reported on the IotaOrigin discord
https://discord.com/channels/950754221031034921/979671432789389352/979817196144427098
For Sanderinho, changing his name to alex34 fixed the problem.

MySparta has since changed his name to ABC123 (https://soonaverse.com/member/0x8b344a3942b6629f57733de8cee8d518d0f49315), but this didn't fix the problem, as ABC123 is still not selectable.

three other exploiters of the guardian bug can't be selected as well.
Cartoya https://soonaverse.com/member/0x46d8eabcca3cafc83ed9bd32e4225fb514f0bbe7/activity
IOTA4LIFE https://soonaverse.com/member/0x1a85f7ad927223eab310f1920b4db0085eb7d2c8/activity
LovIota https://soonaverse.com/member/0x90d81fc02d3e0aaf5575e81faabd596ac380d1b1/activity

**Comment by Doenermaker** [comment]
> Did you try to select by ID? Did that work?

seems like you're on to something, using 0x8b344a3942b6629f57733de8cee8d518d0f49315 worked for mysparta/ABC123

**Comment by adamunchained** [comment]
Yeah I’m not at PC at the moment but there must be an UI bug in the search if you user their username.

**Comment by csxiong** [comment]
I have also received the same feedback from several community members such as @WildWest, @BlackHole, @Stranger. They have all registered or changed their aliases around May 23rd.

**Comment by Eicke-S** [comment]
Same error occurs for user @Eicke since yesterday.

**Comment by adamunchained** [comment]
@gundavri - please change to use Algolia search instead and remove full list “read” on members.
