### ISSUE TITLE
New Homepage does not work on Safari or mobile

### ISSUE THREAD

**Issue by shonuffy** [soonaverse/soonaverse-dao#797]
Videos do not play, per Adam there need to be changes to code submitted by our contracted designer to correct this. Submitting a formal request to Github to help track the issue.

**Comment by adamunchained** [comment]
cool, let me know once the designer finish.

**Comment by shonuffy** [comment]
You said you were going to have to fix this. My developer can't work with the zip file you sent me.

**Comment by shonuffy** [comment]
I am looping back on this. Safari and mobile can't run the videos.

**Comment by adamunchained** [comment]
@Gundavri - can you please check this. see src/assets/static-home - It's a statically exported site we got and it was given us broken. Can you try to see if you can fix the video looping issue in Safari so videos run?

**Comment by adamunchained** [comment]
@shonuffy

@Gundavri - spent few hours on this today.

The problem is that Safari does not support webm format, but currently it's the only one in the web which supports a transparent background. I tried many other formats but could not achieve the result, there is a black background if I use mp4, mov or something else. I think the best way would be if you could provide mp4 versions with a good background and everything so I can just put those videos in their place and it doesn't show any black borders/backgrounds.
