### ISSUE TITLE
#WEN Default price option for token trading

### ISSUE THREAD

**Issue by csxiong** [soonaverse/soonaverse-dao#838]
**Describe the bug**
All the exchanges I have tried use `Limit Price` as the default price option instead of `Market Price`, which can easily cause losses due to user misuse. Please change the default price option to `Limit Price` to match the common user habits.

**Comment by adamunchained** [comment]
Interesting. @humaint was agreed with you @csxiong and I was strongly against it.

I've argued that we should provide easier option first before the more complex one. 

@TangleAccountant - what do you think?

**Comment by TangleAccountant** [comment]
Limit purchasing is definitely the default for the reason mentioned above. My thought was that our most common feedback was that our bid/ask/limit ordering verbiage and design was too "complicated" and since we'll be competing with simple swaps on DEXs that a default market buy made more sense. But maybe we need to lean into the fact that our exchange is capable of more complex orders. I'm okay with making limit orders the default, but we should make it clear that market orders are an option.

On that note. The current implementation of market buys/sells isn't optimal. It just takes the best price, no matter how large the order, and applies it as if there's enough liquidity at that price to satisfy the entire order. The market buy/sell needs to dynamically adjust the price up or down as a large market buy or sell is being consumed.

**Comment by adamunchained** [comment]
ok, no worries. Limit price it is. So what about if we set the default price to 24h average price instead of keeping it zero?

re: market buy - yeah we might need to tweak it once @boldizsar-unchained is back.

**Comment by adamunchained** [comment]
re: market buys/sells it'll be done in separate issue: https://github.com/soonaverse/soonaverse/issues/1329

**Comment by adamunchained** [comment]
changed to defaulting to limit price.
