### ISSUE TITLE
'NFT does not have IPFS media' error upon minting

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#929]
User tries to mint their collection before a sale, but recieves an error, 'NFT does not have IPFS media'. The user since cancelled the sale due to this issue, so the only collection associated with this has been cancelled. The cancelled collection is here: https://soonaverse.com/collection/0x5dd810c0910f11bd0336c3a44a3ad04eaf502eff

Picture of error (note: user had 2 collections that suffered this error, one if which was the collection linked above, but this error screenshot may have been from a different collection, it's hard to tell. Same error message at the same point occured in both collections though so it may not matter)
![nftdoesnothaveipfsmedia-1](https://user-images.githubusercontent.com/38050901/199046161-47e760f3-7a2b-4bdb-b3a8-a4b62287d2e0.png)

Cause unknown.

**Comment by adamunchained** [comment]
This collection is rejected.

**Comment by SeanTMartin** [comment]
The collection being rejected was acknowledged in the body of the issue and is unrelated to the error. It was included for the purpose of identifying a collection this happened to.

User tried to mint NFTS.  Then the user got the error. Then the user rejected the collection so that the upcoming sale wasn't compromised.

**Comment by adamunchained** [comment]
I see sorry I just scanned the issue after I saw collection being rejected.

It takes time to upload files on to the IPFS. It can easily take several hours. We don't allow mint of the collection until the upload to IPFS is finished because it would resulted in immutable NFT data missing link to image on the IPFS. 

When this error occurs user just need to wait. We've an enhancement in the backlog which will significantly speed up this process.
