### ISSUE TITLE
[Payment Issue]: 

### ISSUE THREAD

**Issue by Benzon92** [soonaverse/soonaverse-dao#974]
### Discord Name

G.E.C.K.O.#6589

### Soonaverse Profile Id

0x81f706517ae81DcBF9C22cdbbAC58BF5Fb80E1b1

### Payment Action

Staked Token

### Payment Problem

I made a purchase outside of the time window and did not get a refund.

### Wallet Type

Other (Please describe in comments)

### Wallet Version

2.0.0

### Payment Sent to Address

smr1qq5dj0ddpgslkh44ajlaxkd88jzgz6clyr6qngvc7hrmspycwvfr29gawpr

### Amount Sent

501 SOON

### Comments

```shell
Firefly Shimmer Wallet, No refund on soonaverse possible
```

**Comment by adamunchained** [comment]
Your funds were refunded, see here: https://explorer.shimmer.network/shimmer/block/0x3c99ec7dc420e4a82230753c24cf5467d721806ce5f7289f7db41f56da8e95fc

Also see credit in your transaction history: https://soonaverse.com/member/0x81f706517ae81DcBF9C22cdbbAC58BF5Fb80E1b1/transactions

**Comment by Benzon92** [comment]
Are you serious?! Just closing the ticket... The automatic transaction over the fireflybutton isn´t working, because the amount is wrong. So i have to send it manually. Then there are errors, that i have to set an expirydate and now i have 0,3 soon tokens instead of 501 and you say it is done? How do you explain this? Or is shimmer just as crappy as the rest? 
![Screenshot 2022-12-12 214913](https://user-images.githubusercontent.com/120221438/207151484-08eca2b1-4762-4261-a0b8-2e82aed74cab.png)

**Comment by adamunchained** [comment]
Ticked was closed because you said you've sent 501 SOON but didn't receive it back. Although I've presented you with above transaction about your refund going back to the wallet: https://explorer.shimmer.network/shimmer/block/0x3c99ec7dc420e4a82230753c24cf5467d721806ce5f7289f7db41f56da8e95fc

Address smr1qq5dj0ddpgslkh44ajlaxkd88jzgz6clyr6qngvc7hrmspycwvfr29gawpr received back 501 SOON.
<img width="1396" alt="Screenshot 2022-12-12 at 1 29 01 PM" src="https://user-images.githubusercontent.com/130610/207158538-57e65ea9-018e-4488-8648-f7c7ce1924fa.png">

Am I missing something? 

I'm happy to re-open the issue if that's the case.

**Comment by adamunchained** [comment]
Your refund was in fact stuck. My bad, I didn't check your refund in details.

See credit here: https://explorer.shimmer.network/shimmer/block/0x1f21475b5fd4dd4f4a9f5c1d03f4f48ccce9cb3ba4993c6edd375c7116bfabcc

Your balance is 501 SOON again: https://explorer.shimmer.network/shimmer/addr/smr1qqd6jzm30tla4zgvsmwevuk3s6ugkp5ymtzhcfcxt7px4map98vfwxesu7z

I'll close this issue and we can re-open if any issues.
