### ISSUE TITLE
NFT systeminfo not available (IPFS links)

### ISSUE THREAD

**Issue by CptBananu** [soonaverse/soonaverse-dao#982]
**Describe the bug**
When I click the both links in the sysstem info container of an NFT a new browser tab opens that only says "The owner of this gateway does not have this content pinned to their Pinata account. In order to view this content, please reach out to the owner. - ERR_ID:00006"

This can be reproduced seemingly on any NFT and it doesn't matter if the collection is migrated to Shimmer or not. Also it's no local issue bc another discord member reported this and I could directly reproduce it.
![image](https://user-images.githubusercontent.com/104099536/207543266-fa952fa2-b08d-4c8b-a7c0-63e3c8f6906d.png)

**To Reproduce**
1. Go to any NFT
2. Open the System info container
3. Click on "View" of IPFS Metadata or IPFS Image
4. See following screenshot
![image](https://user-images.githubusercontent.com/104099536/207545026-298ccf47-2f73-499a-8ad7-8620637cfe62.png)

**Comment by adamunchained** [comment]
There is a bug. There have been a change how we handle ipfs.

1. We don't use Pinata anymore hence the ipfs2.soonaverse.com link must be changed
2. We only put images on the IPFS once the collection are actually minted.

Fix:
- we need to hide ipfs Metadata / Image field before collection is minted
- we need to fix the link to use ipfs.io/ipfs instead

It'll be fixed in upcoming release 0.17 so before xmas.
