### ISSUE TITLE
NFTs not appearing in multiple locations

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#985]
Certain NFTs are not displaying in multiple locations.

Location 1: 
This user's profile has 5 NFTs from the collection https://soonaverse.com/collection/0xcea0221ce8e4fb02e709da405942e118b2468192
and is only displaying 2 out of the 5 NFTs (Lunar Buddies - Christmas Edition)
https://soonaverse.com/member/0x6ded3e156c0d8cd07ea2873fd24051269555502a/nfts

Location 2:
The [collection itself](https://soonaverse.com/collection/0xcea0221ce8e4fb02e709da405942e118b2468192) is missing some NFTs from displaying. The collection has 24 items, and 11 left to mint. but only 8 nfts are show on bottom of the page. missing 5 items.

**Comment by CptBananu** [comment]
@adamunchained @humaint 

Here are the links to the corresponding NFTs if this helps u. All have the correct holder but only 2 of 5 are displayed in that users profile. Went through their tx history and was able to find them there.

Missing Lunar Buddy #19: https://soonaverse.com/nft/0x0764a92bfbd2518db2538a78fc0049f4b345f916

Missing Lunar Buddy #14: https://soonaverse.com/nft/0x06712fcf32cb59c8c65db7e9ed7f99aab3c76708

Missing Lunar Buddy #4: https://soonaverse.com/nft/0x3d445cbb741bd4da80075708a66516ed41d1b778

===========

Present Lunar Buddy #9: https://soonaverse.com/nft/0xc1b3dc04467019a9a8c4672788f0eb2adbff8638

Present Lunar Buddy #15: https://soonaverse.com/nft/0x6f3a5b623d97b02fd7e2c0b4bc1b9e93d6212ee5

**Comment by adamunchained** [comment]
Multiple things:
- there was a scrolling issue on collection that it would not load additional results. This has been fixed.
- you might see less NFTs compare to total NFTs on collection because some NFTs could have been withdrawn.

There was an issue with sync into our search indexing database. I've refreshed these records and it now shows correctly. We've change how the sync work in our next release that will hopefully help this.

Note I can see all his four NFTs under his profile except [0x3d445cbb741bd4da80075708a66516ed41d1b778](https://soonaverse.com/nft/0x3d445cbb741bd4da80075708a66516ed41d1b778) that has been withdrawn.
